routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('app', 'MeuControlador@app');
Route::get('multiplicar/{n1}/{n2}', 'MeuControlador@multiplicar');
Route::prefix('/app')->group(function(){
    Route::get('/', 'MeuControlador@app')->name('app');
    Route::get('/user', 'MeuControlador@user')->name('app-user');
    Route::get('/profile', 'MeuControlador@profile')->name('app-profile');
});
Route::get('produtos', function(){
    return view('outras.produtos');
})->name('produtos');
Route::get('departamentos', function(){
    return view('outras.departamentos');
})->name('departamentos');
Route::get('apps', function(){
    return redirect()->route('app');
});
Route::redirect('/', '/app', 301)->name('RedirectApp');

Route::resource('clientes', 'ClienteControlador');

Route::get('opcoes/{opcao?}',function($opcao=null){
    return view('outras.opcoes', compact(['opcao']));
})->name('opcoes');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('bootstrap', function(){
    return view('outras.exemplo');
});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $fillable = ['name'];
}

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    //
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClienteControlador.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ClienteControlador extends Controller
{
    private $clientes = [
        ['id'=>1, 'nome'=>'Ademir'],
        ['id'=>2, 'nome'=>'Jairo'],
        ['id'=>3, 'nome'=>'Clovis'],
        ['id'=>4, 'nome'=>'Moacir']
    ];

    public function __construct(){
        $clientes = session('clientes');
        if(!isset($clientes)){
            session(['clientes' => $this->clientes]);
        }
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$clientes = $this->clientes;
        $clientes = session('clientes');
        //return view('clientes.index', compact(['clientes']));
        return view('clientes.index')->with('clientes', $clientes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $clientes = session('clientes');
        $id = end($clientes)['id'] + 1;
        $nome = $request->nome;
        $dados = ["id"=>$id, "nome"=>$nome];
        $clientes[] = $dados;
        session(['clientes'=>$clientes]);
        $clientes = $this->clientes;
        return redirect()->route('clientes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $clientes = session('clientes');
        $index = $this->getIndex($id, $clientes);
        $cliente = $clientes[$index];

        return view('clientes.info', compact(['cliente']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clientes = session('clientes');
        $index = $this->getIndex($id, $clientes);
        $cliente = $clientes[$index];

        return view('clientes.edit', compact(['cliente']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $clientes = session('clientes');
        $index = $this->getIndex($id, $clientes);
        $cliente = $clientes[$index]['nome'] = $request->nome;
        session(['clientes' => $clientes]);
        return redirect()->route('clientes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $clientes = session('clientes');
        $index = $this->getIndex($id, $clientes);
        array_splice($clientes, $index, 1);
        session(['clientes'=>$clientes]);
        return redirect()->route('clientes.index');
    }

    private function getIndex($id, $clientes){
        $ids = array_column($clientes, 'id');
        $index = array_search($id, $ids);
        return $index;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MeuControlador.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MeuControlador extends Controller
{
    public function app(){
        return view('app');
    }
    public function user(){
        return view('user');
    }
    public function profile(){
        return view('profile');
    }
    public function produtos(){
        return view('produtos');
    }
    public function departamentos(){
        return view('departamentos');
    }
    public function multiplicar($n1, $n2){
        return $n1 * $n2;
    }
}

resources/views/app.blade.php
<ul>
    <li><a href="{{route('app-user')}}">User</a></li>
    <li><a href="{{route('app-profile')}}">Profile</a></li>
    <li><a href="{{route('app')}}">Atualizar</a>  </li>
</ul>

resources/views/clientes/create.blade.php
@extends('layouts.principal')
@section('conteudo')
<h3>Novo Cliente</h3>

<form action="{{ route('clientes.store') }}" method="POST">
    @csrf
    <input type="text" name="nome">
    <input type="submit" value="salvar">
</form>
@endsection

resources/views/clientes/edit.blade.php
@extends('layouts.principal')
@section('conteudo')
<h3>Editar Cliente</h3>

<form action="{{ route('clientes.update', $cliente['id']) }}" method="POST">
    @csrf
    @method('PUT')
    <input type="text" name="nome" value="{{$cliente['nome']}}">
    <input type="submit" value="salvar">
</form>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.principal')
@section('conteudo')

    <h3>Clientes</h3>
    <a href="{{ route('clientes.create') }}">Novo Cliente</a>
    @if(count($clientes)>0)
    <ul>
        @foreach ($clientes as $c)
            <li>
            {{$c['id']}} | {{$c['nome']}} | <a href="{{ route('clientes.edit', $c['id']) }}">Editar</a> <a href="{{ route('clientes.show', $c['id'])}}">Info</a>
            <form action="{{ route('clientes.destroy', $c['id']) }}" method="POST">
                @csrf
                @method('DELETE')
                <input type="submit" value="Remover">
            </form>
            </li>
        @endforeach
    </ul>
    @else
        <h4>Não existem clientes cadastrados.</h4>
    @endif
    @empty($clientes)
    <p>0 Registos</p>
    @endempty
    <!-- @for ($i = 1; $i < count($clientes)+1; $i++)
        {{$i}}
    @endfor -->
    @foreach ($clientes as $item)
        @if ($loop->first)
            (primeiro) | 
        @endif
        <!-- ({{ $loop->index }}) - {{$loop->iteration}} / {{$loop->count}}| -->
        {{$loop->iteration}}
        @if ($loop->last)
            (último)
        @endif
        
    @endforeach

@endsection

resources/views/clientes/info.blade.php
@extends('layouts.principal')
@section('conteudo')
    <h3>Informações do Cliente</h3>

    <p>ID: {{$cliente['id']}}</p>
    <p>Nome: {{$cliente['nome']}}</p>
    <br>
    <a href="{{route('clientes.index')}}">Voltar</p>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/bootstrap.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <meta name="csrf-token" content="{{ csrf_token()}}">
    <title>Pricing example · Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{{asset('/css/app.css')}}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <!--<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json"> -->
    <link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      html {
        font-size: 14px;
        }
        @media (min-width: 768px) {
        html {
            font-size: 16px;
        }
        }

        .container {
        max-width: 960px;
        }

        .pricing-header {
        max-width: 700px;
        }

        .card-deck .card {
        min-width: 220px;
        }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#">Features</a>
    <a class="p-2 text-dark" href="#">Enterprise</a>
    <a class="p-2 text-dark" href="#">Support</a>
    <a class="p-2 text-dark" href="#">Pricing</a>
  </nav>
  <a class="btn btn-outline-primary" href="#">Sign up</a>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Free</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>10 users included</li>
          <li>2 GB of storage</li>
          <li>Email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Pro</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>20 users included</li>
          <li>10 GB of storage</li>
          <li>Priority email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Get started</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Enterprise</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>30 users included</li>
          <li>15 GB of storage</li>
          <li>Phone and email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
      </div>
    </div>
  </div>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="https://getbootstrap.com/docs/4.5/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
          <li><a class="text-muted" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource name</a></li>
          <li><a class="text-muted" href="#">Another resource</a></li>
          <li><a class="text-muted" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>
<script src="{{asset('js/app.js')}}" type="text/javascript"></script>
</body>
</html>

resources/views/layouts/principal.blade.php
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>Views</title>
        <link rel="stylesheet" href="{{asset('css/principal.css')}}">
    </head>
    <body>
        <div class="row">
            <div class="col1 menu">
                <ul>
                    <li><a class="{{request()->routeIs('clientes.*') ? 'active' : ''}}" href="{{ route('clientes.index') }}">Clientes</a></li>
                    <li><a class="{{request()->routeIs('produtos') ? 'active' : ''}}" href="{{ route('produtos') }}">Produtos</a></li>
                    <li><a class="{{request()->routeIs('departamentos') ? 'active' : ''}}" href="{{ route('departamentos') }}">Departamentos</a></li>
                    <li><a class="{{request()->routeIs('opcoes') ? 'active' : ''}}" href="{{ route('opcoes') }}">Opções</a></li>
                </ul>
            </div>
            <div class="col2">
                @yield('conteudo')
            </div>
        </div>
        
    </body>
</html>

resources/views/outras/departamentos.blade.php
@extends('layouts.principal')
@section('conteudo')
<h3>Departamentos</h3>
<ul>
    <li>Computadores</li>
    <li>Eletrônicos</li>
    <li>Acessórios</li>
    <li>Roupas</li>
</ul>

@alerta(['titulo'=> 'Erro', 'tipo'=> 'error'])
<p>Verificar problema</p>
@endalerta

@component('components.alerta', ['titulo'=> 'Erro', 'tipo'=> 'info'])
<p>Verificar problema</p>
@endcomponent
@endsection

resources/views/outras/exemplo.blade.php
@extends('layouts.bootstrap')

@section('conteudo')
    
@endsection

resources/views/outras/opcoes.blade.php
@extends('layouts.principal')
@section('conteudo')

<div class="options">
    <ul>
        <!--<li><a class="warning {{request()->routeIs('opcoes') ? 'selected' : ''}}" href="{{ route('opcoes', 1)}}">Warning</a></li>-->
        <li><a class="warning" href="{{ route('opcoes', 1)}}">Warning</a></li>
        <li><a class="info" href="{{ route('opcoes', 2)}}">Info</a></li>
        <li><a class="success" href="{{ route('opcoes', 3)}}">Success</a></li>
        <li><a class="error" href="{{ route('opcoes', 4)}}">Error</a></li>
    </ul>
</div>

@if(isset($opcao))
    @switch($opcao)
        @case(1)
            @component('components.alerta', ['titulo'=> 'Alerta', 'tipo'=> 'warning'])
            <p>Verificar alerta</p>
            @endcomponent
            @break
        @case(2)
            @component('components.alerta', ['titulo'=> 'Informação', 'tipo'=> 'info'])
            <p>Verificar informação</p>
            @endcomponent
            @break
        @case(3)
            @component('components.alerta', ['titulo'=> 'Sucesso', 'tipo'=> 'success'])
            <p>Verificar sucesso</p>
            @endcomponent
            @break
        @case(4)
            @component('components.alerta', ['titulo'=> 'Erro', 'tipo'=> 'error'])
            <p>Verificar erro</p>
            @endcomponent
            @break
        @default
            
    @endswitch
@endif

@endsection

resources/views/outras/produtos.blade.php
@extends('layouts.principal')
@section('conteudo')
<h3>Produtos</h3>
<ul>
    <li>PC</li>
    <li>Notebook</li>
    <li>Mouse</li>
    <li>Camiseta Polo</li>
</ul>

@endsection

resources/views/profile.blade.php
Tela profile<br>
<a href="{{route('app')}}">Voltar</a>

resources/views/user.blade.php
Olá, esta é a tela user<br>
<a href="{{route('app')}}">Voltar</a>